os: linux
dist: bionic
language: go
go:
  - 1.14.x
services:
  - docker
before_script:
  - sudo chmod 755 /etc/docker

addons:
  apt:
    packages:
      - "libgpgme-dev"
      - "libdevmapper-dev"

stages:
  - deploy
  - deploy-multi-arch

.build-image-for-arch: &build-image-for-arch |
  stage: deploy
  script: bash hack/deploy.sh
  skip_cleanup: true
  on:
    all_branches: true

jobs:
  include:

  # Build and push the image for amd64
  - stage: deploy
    <<: *build-image-for-arch
  name: Build image for kata-operator-daemon (amd64)
  arch: amd64

  # Build and push the image for ppc64le
  - stage: deploy
    <<: *build-image-for-arch
  name: Build image for kata-operator-daemon (ppc64le)
  arch: ppc64le

  # Build and push the image for s390x
  - stage: deploy
    <<: *build-image-for-arch
  name: Build image for kata-operator-daemon (s390x)
  arch: s390x

  - stage: deploy-multi-arch
    name: Deploy multi-arch manifest
    script: bash hack/deploy-multi-arch.sh
    skip_cleanup: true
    on:
      all_branches: true
